on:
  pull_request:
    types:
      - closed

jobs:
  base:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.base_version }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.sha }}
      - name: version
        run: echo "base_version=$(jq -r .version < package.json)" >> "$GITHUB_OUTPUT"
  current:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.current_version }}
    steps:
      - uses: actions/checkout@v3
      - name: version
        run: echo "current_version=$(jq -r .version < package.json)" >> "$GITHUB_OUTPUT"
  compare:
    needs: [base, current]
    runs-on: ubuntu-latest
    steps:
      - name: Compare
        run: echo ${{needs.base.outputs.version}} ${{needs.current.outputs.version}}
