on:
  pull_request:
    types:
      - closed

# jobs:
#   base:
#     if: github.event.pull_request.merged == true
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           ref: ${{ github.event.pull_request.base.sha }}
#       - name: base_version
#         run: echo "test=$(jq -r .version < package.json)" >> "$GITHUB_OUTPUT"
#       - uses: actions/checkout@v3
#       - name: current_version
#         run: echo "test=$(jq -r .version < package.json)" >> "$GITHUB_OUTPUT"
#       - name: compare
#         run: echo ${{ steps.base_version.outputs.test }} ${{ steps.current_version.outputs.test }}

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
