name: merge

on:
  pull_request:
    types:
      - closed

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.sha }}
      - id: base
        run: echo "version=$(jq -r .version < package.json)" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v3
      - id: current
        run: echo "version=$(jq -r .version < package.json)" >> "$GITHUB_OUTPUT"
      - name: compare
        run: echo ${{ steps.base.outputs.version }} ${{ steps.current.outputs.version }}
