on:
  pull_request:
    types:
      - closed

# jobs:
#   base:
#     if: github.event.pull_request.merged == true
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           ref: ${{ github.event.pull_request.base.sha }}
#       - name: base_version
#         run: echo "test=$(jq -r .version < package.json)" >> "$GITHUB_OUTPUT"
#       - uses: actions/checkout@v3
#       - name: current_version
#         run: echo "test=$(jq -r .version < package.json)" >> "$GITHUB_OUTPUT"
#       - name: compare
#         run: echo ${{ steps.base_version.outputs.test }} ${{ steps.current_version.outputs.test }}

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      base_version: ${{ steps.step1.outputs.test }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.sha }}
      - id: step1
        run: echo "test=$(jq -r .version < package.json)" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    outputs:
      current_version: ${{ steps.step1.outputs.test }}
    steps:
      - uses: actions/checkout@v3
      - id: step1
        run: echo "test=$(jq -r .version < package.json)" >> "$GITHUB_OUTPUT"
  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.base_version}}
          OUTPUT2: ${{needs.job2.outputs.current_version}}
        run: echo "$OUTPUT1 $OUTPUT2"
